--- #YAML:1.0
name:               Mail-IMAPClient
version:            3.35
abstract:           IMAP4 client library
author:
    - Phil Pearl (Lobbes) <phil@zimbra.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:               0
    Errno:              0
    Fcntl:              0
    File::Temp:         0
    IO::File:           0
    IO::Select:         0
    IO::Socket:         0
    IO::Socket::INET:   1.26
    List::Util:         0
    MIME::Base64:       0
    Parse::RecDescent:  1.94
    perl:               5.008
    Test::More:         0
resources:
    bugtracker:
        mailto:  bug-Mail-IMAPClient@rt.cpan.org
        web:     http://rt.cpan.org/Public/Dist/Display.html?Name=Mail-IMAPClient
    homepage:  http://sourceforge.net/projects/mail-imapclient/
    repository:
        type:  git
        url:   git://git.code.sf.net/p/mail-imapclient/git
        web:   http://sourceforge.net/p/mail-imapclient/git/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
